version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
    depends_on:
      - db
    ports:
      - "8050:8050"
    volumes:
      - ./app:/app
      - ./Backup:/home/pi/Backup
    env_file:
      - .env
    command: >
      bash -c "
        python extract_and_load_portfolio.py &&
        python extract_and_load_starlist.py &&
        python app.py
      "

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   # Change this to your preferred email
      PGADMIN_DEFAULT_PASSWORD: admin  # Change this to your preferred password
    ports:
      - "5050:80" 
    depends_on:
      - db

volumes:
  postgres_data: