version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
    depends_on:
      - db
    ports:
      - "8050:8050"
    volumes:
      - ./app:/app
    command: >
      bash -c "
        python extract_and_load.py &&
        python app.py
      "

volumes:
  postgres_data: